/* ================================================================
   ТРЕКИ — редактируй только этот блок!

   ПЕРЕМЕННЫЕ КАРТОЧКИ:
     music          → файл музыки
     cover          → файл обложки
     character      → имя персонажа (крупный текст над обложкой)
     title          → название трека (мелкий текст под сердечком)

   ЦВЕТА КАРТОЧКИ:
     cardColor      → фон карточки
     btnColor       → фон кнопки play
     btnText        → иконка внутри кнопки play (треугольник/пауза)
     charColor      → цвет имени персонажа
     titleColor     → цвет названия трека
     skipColor      → цвет стрелок пред/след и иконки громкости
     progressBg     → задняя линия прогресс-бара (пустая часть)
     progressFill   → заполненная часть прогресс-бара и сердечко-ползунок
     timeColor      → цвет таймеров (0:00 / 0:00)
     modeColor      → цвет иконок шафл и повтор (неактивное состояние)
     popupBg        → фон попапа громкости
     popupBorder    → контур попапа громкости
     popupTrack     → задняя линия слайдера громкости
     popupThumb     → ползунок слайдера громкости
     creditName     → цвет имён художника и музыканта
     creditLabel    → цвет подписей "Art by" / "Music by"

   СЕРДЕЧКО:
     heartDefault   → форма SVG нелайкнутого сердца: "down" (обычное) или "up" (перевёрнутое)
     heartUnliked   → (опционально) картинка вместо SVG когда не лайкнуто, например "heart_empty.png"
                      если не указано или пусто — используется SVG из heartDefault
     heartLiked     → картинка лайкнутого сердца: "heart1.png", "heart2.png" и т.д.
     heartColor     → цвет контура SVG сердца (используется только если heartUnliked не указан)
     heartSize      → размер иконки сердца в пикселях (применяется к лайкнутой и нелайкнутой форме), по умолчанию 36
================================================================ */
const TRACKS = [
  {
    music:         "mondaymania.m4a",
    cover:         "cover1.gif",
    character:     "Sansfield",
    title:         "Mondaymania",
    cardColor:     "#ffffff",
    btnColor:      "#EE670D",
    btnText:       "#ffffff",
    charColor:     "#000000",
    titleColor:    "rgba(0,0,0,0.4)",
    skipColor:     "rgba(0,0,0,0.35)",
    progressBg:    "rgba(0,0,0,0.12)",
    progressFill:  "#EE670D",
    timeColor:     "rgba(0,0,0,0.38)",
    modeColor:     "rgba(0,0,0,0.35)",
    popupBg:       "#ffffff",
    popupBorder:   "rgba(0,0,0,0.15)",
    popupTrack:    "rgba(0,0,0,0.12)",
    popupThumb:    "#EE670D",
    creditName:    "rgba(0,0,0,0.85)",
    creditLabel:   "rgba(0,0,0,0.5)",
    heartUnliked:  "heart1_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart1.png",
    heartColor:    "#000000",
    heartSize:     40,
    artName:       "Бабуля Лютик",
    artUrl:        "https://t.me/buttercupCD",
    musicName:     "aytanner",
    musicUrl:      "https://www.youtube.com/watch?v=5kt2nZ8QUVo&list=RD5kt2nZ8QUVo&start_radio=1",
    auName:        "",
    auUrl:         "",
  },
  {
    music:         "Underverse OST - Rekindle.m4a",
    cover:         "cover2.png",
    character:     "X!Gaster",
    title:         "Underverse OST - Rekindle",
    cardColor:     "#221F28",
    btnColor:      "#7C6994",
    btnText:       "#221F28",
    charColor:     "#7C6994",
    titleColor:    "rgba(124,105,148,0.6)",
    skipColor:     "#605c63",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#7C6994",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#605c63",
    popupBg:       "#221F28",
    popupBorder:   "#605c63",
    popupTrack:    "#605c63",
    popupThumb:    "#7C6994",
    creditName:    "rgba(255,255,255,0.92)",
    creditLabel:   "rgba(255,255,255,0.5)",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart2.png",
    heartColor:    "#7C6994",
    heartSize:     36,
    artName:       "джекич йоу.",
    artUrl:        "https://t.me/nevermorerrrjack",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=h2MTvNBsgl4&list=RDh2MTvNBsgl4&start_radio=1",
    auName:        "Jakei95",
    auUrl:         "",
  },
  {
    music:         "reaper.m4a",
    cover:         "cover3.png",
    character:     "Reaper",
    title:         "ReaperTale Megalovania",
    cardColor:     "#151A1F",
    btnColor:      "#4EC9CE",
    btnText:       "#151A1F",
    charColor:     "#4EC9CE",
    titleColor:    "rgba(78,201,206,0.6)",
    skipColor:     "#434C55",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#4EC9CE",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#434C55",
    popupBg:       "#151A1F",
    popupBorder:   "#434C55",
    popupTrack:    "#434C55",
    popupThumb:    "#4EC9CE",
    creditName:    "rgba(255,255,255,0.92)",
    creditLabel:   "rgba(255,255,255,0.5)",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart3.png",
    heartColor:    "#4EC9CE",
    heartSize:     36,
    artName:       "Тундра",
    artUrl:        "https://t.me/tendremur",
    musicName:     "Fire Music",
    musicUrl:      "https://www.youtube.com/watch?v=iAKsg3xGYek",
    auName:        "Renrink",
    auUrl:         "",
  },
  {
    music:         "Lustalovania.m4a",
    cover:         "cover4.png",
    character:     "Lust",
    title:         "Lustalovania",
    cardColor:     "#3C1D86",
    btnColor:      "#9CF1F6",
    btnText:       "#3C1D86",
    charColor:     "#9CF1F6",
    titleColor:    "#9CF1F6",
    skipColor:     "#96319F",
    progressBg:    "#96319F",
    progressFill:  "#9CF1F6",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#96319F",
    popupBg:       "#3C1D86",
    popupBorder:   "#96319F",
    popupTrack:    "#96319F",
    popupThumb:    "#9CF1F6",
    creditName:    "#9CF1F6",
    creditLabel:   "#9CF1F6",
    heartUnliked:  "heart4_empty.png",
    heartDefault:  "down",
    heartLiked:    "heart4.png",
    heartColor:    "#9CF1F6",
    heartSize:     44,
    artName:       "Karra",
    artUrl:        "https://t.me/Directors_02",
    musicName:     "GrowlingPanda",
    musicUrl:      "https://www.youtube.com/watch?v=B4TpEPRah4Q",
    auName:        "NSFWShameCave",
    auUrl:         "",
  },
  {
    music:         "Mismatch.mp3",
    cover:         "cover5.png",
    character:     "Error",
    title:         "Mismatch",
    cardColor:     "#10142D",
    btnColor:      "#A20A00",
    btnText:       "#10142D",
    charColor:     "#FDBD03",
    titleColor:    "rgba(253,189,3,0.6)",
    skipColor:     "#FDBD03",
    progressBg:    "rgba(255,255,255,0.12)",
    progressFill:  "#A20A00",
    timeColor:     "rgba(255,255,255,0.38)",
    modeColor:     "#FDBD03",
    popupBg:       "#10142D",
    popupBorder:   "#FDBD03",
    popupTrack:    "rgba(255,255,255,0.12)",
    popupThumb:    "#A20A00",
    creditName:    "#FDBD03",
    creditLabel:   "#FDBD03",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart5.png",
    heartColor:    "#0508AD",
    heartSize:     36,
    artName:       "Nera_7",
    artUrl:        "https://t.me/unlandd",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=HeTR6Rt3WNs&list=RDHeTR6Rt3WNs&start_radio=1",
    auName:        "Crayon Queen",
    auUrl:         "",
  },
  {
    music:         "waiting_for_you.m4a",
    cover:         "cover6.png",
    character:     "Error and Ink",
    title:         "Waiting For You",
    cardColor:     "#0c0c16",
    btnColor:      "#6b67dd",
    btnText:       "#0c0c16",
    charColor:     "#6b67dd",
    titleColor:    "#6b67dd",
    skipColor:     "#353362",
    progressBg:    "#353362",
    progressFill:  "#6b67dd",
    timeColor:     "#353362",
    modeColor:     "#353362",
    popupBg:       "#0c0c16",
    popupBorder:   "#353362",
    popupTrack:    "#353362",
    popupThumb:    "#6b67dd",
    creditName:    "#6b67dd",
    creditLabel:   "#6b67dd",
    heartUnliked:  "heart6_empty.png",
    heartDefault:  "down",
    heartLiked:    "heart6.png",
    heartColor:    "#e63950",
    heartSize:     48,
    artName:       "acrolein",
    artUrl:        "https://t.me/acro_ein",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=bxbYUOWZZIs&list=RDx3Z5iyJ-gBg&index=5",
    auName:        "Crayon Queen and Comyet",
    auUrl:         "",
  },
  {
    music:         "birdtale.m4a",
    cover:         "cover7.png",
    character:     "Bird",
    title:         "Birdtale - Megalovania",
    cardColor:     "#424E64",
    btnColor:      "#B7C6E7",
    btnText:       "#424E64",
    charColor:     "#93B7EB",
    titleColor:    "#738ccc",
    skipColor:     "#737F97",
    progressBg:    "#526373",
    progressFill:  "#8FB8EE",
    timeColor:     "#67768B",
    modeColor:     "#737F97",
    popupBg:       "#5F6975",
    popupBorder:   "#7E8DA0",
    popupTrack:    "#A2B0CB",
    popupThumb:    "#8A98BF",
    creditName:    "#738ccc",
    creditLabel:   "#b4c4dd",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart7.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "MORI",
    artUrl:        "https://t.me/RiWasHere ",
    musicName:     "The Team Players",
    musicUrl:      "https://www.youtube.com/watch?v=QRZ3JOVI8T4",
    auName:        "Star Somsatang",
    auUrl:         "",
  },
  {
    music:         "eyes_of_a_killer.m4a",
    cover:         "cover8.png",
    character:     "Killer",
    title:         "Eyes of a Killer",
    cardColor:     "#270d0d",
    btnColor:      "#d12525",
    btnText:       "#270d0d",
    charColor:     "#d12525",
    titleColor:    "#d12525",
    skipColor:     "#574242",
    progressBg:    "#574242",
    progressFill:  "#d12525",
    timeColor:     "#d12525",
    modeColor:     "#574242",
    popupBg:       "#270d0d",
    popupBorder:   "#574242",
    popupTrack:    "#574242",
    popupThumb:    "#d12525",
    creditName:    "#d12525",
    creditLabel:   "#d12525",
    heartUnliked:  "heart8_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart8.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "KillerVtomate",
    artUrl:        "https://t.me/KillerVtomate",
    musicName:     "xXtha",
    musicUrl:      "https://www.youtube.com/watch?v=DJemBb0IsEw",
    auName:        "Rahafwabas",
    auUrl:         "",
  },
  {
    music:         "occisor.m4a",
    cover:         "cover9.png",
    character:     "Killer",
    title:         "Occisor",
    cardColor:     "#1F0100",
    btnColor:      "#EF473C",
    btnText:       "#1F0100",
    charColor:     "#EF473C",
    titleColor:    "#EF473C",
    skipColor:     "#382027",
    progressBg:    "#382027",
    progressFill:  "#EF473C",
    timeColor:     "#EF473C",
    modeColor:     "#382027",
    popupBg:       "#1F0100",
    popupBorder:   "#382027",
    popupTrack:    "#382027",
    popupThumb:    "#EF473C",
    creditName:    "#EF473C",
    creditLabel:   "#EF473C",
    heartUnliked:  "heart9_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart9.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "Directed by",
    artUrl:        "https://t.me/mixedevery",
    musicName:     "NyxTheShield",
    musicUrl:      "https://www.youtube.com/watch?v=Wmo_micjtIU",
    auName:        "Rahafwabas",
    auUrl:         "",
  },
  {
    music:         "chromatica.m4a",
    cover:         "cover10.png",
    character:     "Ink",
    title:         "Chromatica",
    cardColor:     "#f5ebdc",
    btnColor:      "#D44926",
    btnText:       "#f5ebdc",
    charColor:     "#D44926",
    titleColor:    "#D44926",
    skipColor:     "#e2c5a9",
    progressBg:    "#e2c5a9",
    progressFill:  "#D44926",
    timeColor:     "#D44926",
    modeColor:     "#e2c5a9",
    popupBg:       "#f5ebdc",
    popupBorder:   "#e2c5a9",
    popupTrack:    "#e2c5a9",
    popupThumb:    "#D44926",
    creditName:    "#D44926",
    creditLabel:   "#D44926",
    heartUnliked:  "heart10_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart10.png",
    heartColor:    "#95B6EC",
    heartSize:     40,
    artName:       "Mundverse",
    artUrl:        "https://t.me/MundoVerse",
    musicName:     "xXtha",
    musicUrl:      "https://www.youtube.com/watch?v=Kl6_fNry67c&list=RDKl6_fNry67c&start_radio=1",
    auName:        "Comyet",
    auUrl:         "",
  },
  {
    music:         "dusha_is_chernil.m4a",
    cover:         "cover11.png",
    character:     "Ink",
    title:         "Душа из чернил",
    cardColor:     "#fddfb3",
    btnColor:      "#792803",
    btnText:       "#fddfb3",
    charColor:     "#792803",
    titleColor:    "#792803",
    skipColor:     "#daad88",
    progressBg:    "#daad88",
    progressFill:  "#792803",
    timeColor:     "#792803",
    modeColor:     "#daad88",
    popupBg:       "#fddfb3",
    popupBorder:   "#daad88",
    popupTrack:    "#daad88",
    popupThumb:    "#792803",
    creditName:    "#792803",
    creditLabel:   "#792803",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart11.png",
    heartColor:    "#792803",
    heartSize:     36,
    artName:       "Rafael_star",
    artUrl:        "https://t.me/Rafael_star",
    musicName:     "SiRus",
    musicUrl:      "https://www.youtube.com/watch?v=CyqCacEMP-g&list=RDCyqCacEMP-g&start_radio=1",
    auName:        "Comyet",
    auUrl:         "",
  },
  {
    music:         "strings_of_euphoria.m4a",
    cover:         "cover12.png",
    character:     "Hush",
    title:         "Strings of Euphoria",
    cardColor:     "#252326",
    btnColor:      "#EAD57A",
    btnText:       "#252326",
    charColor:     "#EAD57A",
    titleColor:    "#EAD57A",
    skipColor:     "#5A555C",
    progressBg:    "#5A555C",
    progressFill:  "#EAD57A",
    timeColor:     "#EAD57A",
    modeColor:     "#5A555C",
    popupBg:       "#252326",
    popupBorder:   "#5A555C",
    popupTrack:    "#5A555C",
    popupThumb:    "#EAD57A",
    creditName:    "#EAD57A",
    creditLabel:   "#EAD57A",
    heartUnliked:  "heart12_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart12.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "Sourcan",
    artUrl:        "https://t.me/sourcan",
    musicName:     "xXtha",
    musicUrl:      "https://www.youtube.com/watch?v=0-ycb_6Qr18&list=RD0-ycb_6Qr18&start_radio=1",
    auName:        "admixverse-official",
    auUrl:         "",
  },
  {
    music:         "i_miss_you_no_lyrics.m4a",
    cover:         "cover13.png",
    character:     "Dust",
    title:         "I MISS YOU - no lyrics",
    cardColor:     "#000031",
    btnColor:      "#BA01FE",
    btnText:       "#000031",
    charColor:     "#BA01FE",
    titleColor:    "#BA01FE",
    skipColor:     "#2D3356",
    progressBg:    "#2D3356",
    progressFill:  "#BA01FE",
    timeColor:     "#BA01FE",
    modeColor:     "#2D3356",
    popupBg:       "#000031",
    popupBorder:   "#2D3356",
    popupTrack:    "#2D3356",
    popupThumb:    "#BA01FE",
    creditName:    "#BA01FE",
    creditLabel:   "#BA01FE",
    heartUnliked:  "",
    heartDefault:  "up",
    heartLiked:    "heart13.png",
    heartColor:    "#BA01FE",
    heartSize:     36,
    artName:       "Сорняк",
    artUrl:        "https://t.me/sornyaky",
    musicName:     "Wega",
    musicUrl:      "https://www.youtube.com/watch?v=axIuk8dRITs",
    auName:        "Ask-Dusttale",
    auUrl:         "",
  },
  {
    music:         "hello_world_sharax.m4a",
    cover:         "cover14.png",
    character:     "Fatal Error",
    title:         "Hello World",
    cardColor:     "#06092B",
    btnColor:      "#E03165",
    btnText:       "#06092B",
    charColor:     "#E03165",
    titleColor:    "#E03165",
    skipColor:     "#60B29C",
    progressBg:    "#60B29C",
    progressFill:  "#E03165",
    timeColor:     "#E03165",
    modeColor:     "#60B29C",
    popupBg:       "#06092B",
    popupBorder:   "#60B29C",
    popupTrack:    "#60B29C",
    popupThumb:    "#E03165",
    creditName:    "#E03165",
    creditLabel:   "#E03165",
    heartUnliked:  "heart14_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart14.png",
    heartColor:    "#E03165",
    heartSize:     40,
    artName:       "Loki",
    artUrl:        "https://t.me/LokiTale",
    musicName:     "SharaX",
    musicUrl:      "https://www.youtube.com/watch?v=cVAV-afgaYI",
    auName:        "",
    auUrl:         "",
  },
  {
    music:         "golden_grace.m4a",
    cover:         "cover15.png",
    character:     "Dream",
    title:         "Golden Grace",
    cardColor:     "#3e5e5a",
    btnColor:      "#E6892C",
    btnText:       "#3e5e5a",
    charColor:     "#E6892C",
    titleColor:    "#E6892C",
    skipColor:     "#2c4240",
    progressBg:    "#2c4240",
    progressFill:  "#E6892C",
    timeColor:     "#E6892C",
    modeColor:     "#2c4240",
    popupBg:       "#3e5e5a",
    popupBorder:   "#2c4240",
    popupTrack:    "#2c4240",
    popupThumb:    "#E6892C",
    creditName:    "#E6892C",
    creditLabel:   "#E6892C",
    heartUnliked:  "heart15_empty.png",
    heartDefault:  "up",
    heartLiked:    "heart15.png",
    heartColor:    "#95B6EC",
    heartSize:     36,
    artName:       "Лисий оладушек",
    artUrl:        "https://t.me/TokiDofamin",
    musicName:     "FrostFM",
    musicUrl:      "https://www.youtube.com/watch?v=mbsCNdeQQRs",
    auName:        "",
    auUrl:         "",
  },
];